from __future__ import annotations

import hashlib
import mimetypes
import socket
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path
from urllib.parse import quote, urlparse

import httpx

from .config import settings


@lru_cache(maxsize=1)
def _rest_client():
    if not settings.supabase_ready:
        raise RuntimeError("Supabase REST Storage is not configured")
    from supabase import create_client
    return create_client(settings.supabase_url, settings.supabase_secret_key)


def storage_configured() -> bool:
    # Prefer S3 because it uses the dedicated Storage endpoint and avoids the
    # project REST hostname DNS issue observed on Render.
    return settings.s3_ready or settings.supabase_ready


def storage_ready() -> bool:
    # Configuration readiness only. Live reachability is exposed by diagnostics.
    return storage_configured()


def _dns(host: str | None, port: int = 443) -> tuple[bool, str | None]:
    if not host:
        return False, "Host fehlt."
    try:
        socket.getaddrinfo(host, port, type=socket.SOCK_STREAM)
        return True, None
    except Exception as exc:
        return False, f"DNS-Auflösung fehlgeschlagen: {type(exc).__name__}: {exc}"


def _client_error_details(exc: Exception) -> dict:
    """Return safe S3 error diagnostics without leaking credentials."""
    try:
        response = getattr(exc, "response", {}) or {}
        err = response.get("Error", {}) or {}
        meta = response.get("ResponseMetadata", {}) or {}
        return {
            "s3_error_code": err.get("Code"),
            "s3_error_message": err.get("Message"),
            "s3_http_status": meta.get("HTTPStatusCode"),
            "s3_request_id": meta.get("RequestId"),
        }
    except Exception:
        return {}


def _object_url(bucket: str, key: str | None = None, query: str | None = None) -> str:
    endpoint = (settings.s3_endpoint or "").rstrip("/")
    url = f"{endpoint}/{quote(bucket, safe='')}"
    if key is not None:
        # Keep slash separators in object keys while encoding each component.
        encoded = "/".join(quote(part, safe="") for part in key.split("/"))
        url += f"/{encoded}"
    if query:
        url += "?" + query
    return url


def _signed_request(method: str, url: str, *, body: bytes = b"", headers: dict | None = None, timeout: float = 20.0) -> httpx.Response:
    """Send a SigV4 request to Supabase's S3 endpoint without boto3 routing.

    Botocore's S3 signer is retained, but request construction is explicit so
    the `/storage/v1/s3` endpoint prefix is preserved exactly. This also gives
    us the raw response body for useful diagnostics when the gateway returns a
    generic 400.
    """
    if not settings.s3_ready:
        raise RuntimeError("Supabase S3 Storage is not configured")

    from botocore.auth import S3SigV4Auth
    from botocore.awsrequest import AWSRequest
    from botocore.credentials import Credentials

    hdrs = dict(headers or {})
    # Supabase implements SigV4 and PutObject Content-Type. Sending an explicit
    # SHA256 avoids transfer-encoding / streaming-signature variants.
    hdrs.setdefault("x-amz-content-sha256", hashlib.sha256(body).hexdigest())
    req = AWSRequest(method=method.upper(), url=url, data=body, headers=hdrs)
    creds = Credentials(settings.s3_access_key_id, settings.s3_secret_access_key)
    S3SigV4Auth(creds, "s3", settings.s3_region).add_auth(req)
    prepared = req.prepare()
    # httpx accepts the signed header mapping as generated by botocore.
    return httpx.request(
        method.upper(),
        url,
        content=body if method.upper() not in {"GET", "HEAD", "DELETE"} else None,
        headers=dict(prepared.headers.items()),
        timeout=timeout,
        follow_redirects=False,
    )


def _safe_response_details(response: httpx.Response | None) -> dict:
    if response is None:
        return {}
    body = ""
    try:
        body = response.text[:800]
    except Exception:
        pass
    return {
        "raw_http_status": response.status_code,
        "raw_response_content_type": response.headers.get("content-type"),
        "raw_response_body": body or None,
        "raw_request_id": response.headers.get("x-amz-request-id") or response.headers.get("x-request-id"),
    }


def _write_probe() -> dict:
    """Write, verify and delete a tiny health object.

    The probe is intentionally isolated under `_health/` and removed in a
    finally block. A successful roundtrip proves the exact operations needed by
    card image persistence instead of relying on bucket metadata alone.
    """
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
    key = f"_health/render-probe-{stamp}.txt"
    payload = b"sportscard-vault-s3-probe"
    result = {
        "write_probe_key": key,
        "write_probe_put_ok": False,
        "write_probe_head_ok": False,
        "write_probe_delete_ok": False,
    }
    try:
        put = _signed_request(
            "PUT",
            _object_url(settings.supabase_bucket, key),
            body=payload,
            headers={"content-type": "text/plain"},
        )
        result["write_probe_put_status"] = put.status_code
        if put.status_code not in {200, 201, 204}:
            result.update({"write_probe_error_stage": "put", **_safe_response_details(put)})
            return result
        result["write_probe_put_ok"] = True

        head = _signed_request("HEAD", _object_url(settings.supabase_bucket, key))
        result["write_probe_head_status"] = head.status_code
        result["write_probe_head_ok"] = head.status_code in {200, 204}
        if not result["write_probe_head_ok"]:
            result.update({"write_probe_error_stage": "head", **_safe_response_details(head)})
            return result
        return result
    except Exception as exc:
        result["write_probe_error_stage"] = result.get("write_probe_error_stage") or "request"
        result["write_probe_exception"] = f"{type(exc).__name__}: {exc}"
        return result
    finally:
        try:
            delete = _signed_request("DELETE", _object_url(settings.supabase_bucket, key))
            result["write_probe_delete_status"] = delete.status_code
            result["write_probe_delete_ok"] = delete.status_code in {200, 202, 204}
        except Exception as exc:
            result["write_probe_delete_error"] = f"{type(exc).__name__}: {exc}"


def storage_diagnostics() -> dict:
    if settings.s3_ready:
        host = urlparse(settings.s3_endpoint or "").hostname
        dns_ok, dns_error = _dns(host)
        out = {
            "provider": "supabase-s3",
            "configured": True,
            "bucket": settings.supabase_bucket,
            "host": host,
            "endpoint": settings.s3_endpoint,
            "region": settings.s3_region,
            "dns_ok": dns_ok,
            "bucket_exists": False,
            "object_access_ok": False,
            "bucket_probe_method": None,
            "access_key_configured": bool(settings.s3_access_key_id),
            "secret_key_configured": bool(settings.s3_secret_access_key),
            "endpoint_from_env": bool(settings.s3_endpoint_env),
            "region_from_env": bool(settings.s3_region_env),
            "error": dns_error,
        }
        if not dns_ok:
            return out

        # V0.15.8: use an explicit SigV4 request so the Supabase endpoint path
        # prefix is preserved verbatim and surface the raw gateway error body.
        try:
            list_url = _object_url(settings.supabase_bucket, query="list-type=2&max-keys=1")
            response = _signed_request("GET", list_url)
            out["bucket_probe_method"] = "raw_sigv4_list_objects_v2"
            out.update(_safe_response_details(response))
            if response.status_code == 200:
                out["bucket_exists"] = True
                out["object_access_ok"] = True
                out["error"] = None
                return out
            out["error"] = f"Raw ListObjectsV2 fehlgeschlagen: HTTP {response.status_code}"
        except Exception as exc:
            out["error"] = f"Raw ListObjectsV2 fehlgeschlagen: {type(exc).__name__}: {exc}"

        # A write/read/delete probe tests the exact access pattern required by
        # the scanner. It is tiny, isolated and automatically cleaned up.
        probe = _write_probe()
        out.update(probe)
        if probe.get("write_probe_put_ok") and probe.get("write_probe_head_ok"):
            out["bucket_exists"] = True
            out["object_access_ok"] = True
            out["bucket_probe_method"] = "write_head_delete_probe"
            out["error"] = None
        return out

    # Legacy REST fallback kept for compatibility while S3 credentials are not set.
    out = {
        "provider": "supabase-rest" if settings.supabase_ready else "local",
        "configured": bool(settings.supabase_ready),
        "s3_credentials_configured": settings.s3_credentials_ready,
        "s3_endpoint_candidate": settings.s3_endpoint,
        "s3_region_candidate": settings.s3_region,
        "s3_access_key_configured": bool(settings.s3_access_key_id),
        "s3_secret_key_configured": bool(settings.s3_secret_access_key),
        "bucket": settings.supabase_bucket if settings.supabase_ready else None,
        "host": settings.supabase_host,
        "endpoint": settings.supabase_url,
        "region": None,
        "dns_ok": False,
        "bucket_exists": False,
        "object_access_ok": False,
        "error": None,
    }
    if not settings.supabase_ready:
        out["error"] = "Persistent Image Storage ist nicht konfiguriert."
        return out
    dns_ok, dns_error = _dns(settings.supabase_host)
    out["dns_ok"] = dns_ok
    out["error"] = dns_error
    if not dns_ok:
        return out
    try:
        buckets = _rest_client().storage.list_buckets() or []
        names = []
        for b in buckets:
            if isinstance(b, dict):
                names.append(b.get("name") or b.get("id"))
            else:
                names.append(getattr(b, "name", None) or getattr(b, "id", None))
        out["bucket_exists"] = settings.supabase_bucket in names
        out["object_access_ok"] = out["bucket_exists"]
        if not out["bucket_exists"]:
            out["error"] = f"Storage-Bucket '{settings.supabase_bucket}' wurde nicht gefunden."
    except Exception as exc:
        out["error"] = f"Storage-Abfrage fehlgeschlagen: {type(exc).__name__}: {exc}"
    return out


def persist_image(local_path: str | None, prefix: str, side: str) -> str | None:
    """Persist one scan image, preferring Supabase's S3-compatible API."""
    if not local_path:
        return None
    path = Path(local_path)
    if not path.exists():
        return local_path
    ext = path.suffix.lower() or ".jpg"
    object_path = f"scans/{prefix}/{side}{ext}"
    content_type = mimetypes.guess_type(path.name)[0] or "image/jpeg"

    if settings.s3_ready:
        try:
            body = path.read_bytes()
            response = _signed_request(
                "PUT",
                _object_url(settings.supabase_bucket, object_path),
                body=body,
                headers={"content-type": content_type},
                timeout=45.0,
            )
            if response.status_code not in {200, 201, 204}:
                raise RuntimeError(f"S3 PutObject HTTP {response.status_code}: {response.text[:500]}")
            return f"s3://{settings.supabase_bucket}/{object_path}"
        except Exception:
            return local_path

    if settings.supabase_ready:
        try:
            with path.open("rb") as fh:
                _rest_client().storage.from_(settings.supabase_bucket).upload(
                    path=object_path,
                    file=fh,
                    file_options={"content-type": content_type, "upsert": "false"},
                )
            return f"sb://{settings.supabase_bucket}/{object_path}"
        except Exception:
            return local_path

    return local_path


def signed_url(ref: str | None, expires_in: int = 3600) -> str | None:
    if not ref:
        return None

    if ref.startswith(("s3://", "sb://")):
        _, rest = ref.split("://", 1)
        bucket, object_path = rest.split("/", 1)
        if settings.s3_ready:
            try:
                from botocore.auth import S3SigV4QueryAuth
                from botocore.awsrequest import AWSRequest
                from botocore.credentials import Credentials

                url = _object_url(bucket, object_path)
                req = AWSRequest(method="GET", url=url)
                creds = Credentials(settings.s3_access_key_id, settings.s3_secret_access_key)
                S3SigV4QueryAuth(creds, "s3", settings.s3_region, expires=expires_in).add_auth(req)
                return req.url
            except Exception:
                return None
        if ref.startswith("sb://") and settings.supabase_ready:
            try:
                result = _rest_client().storage.from_(bucket).create_signed_url(object_path, expires_in)
                if isinstance(result, dict):
                    return result.get("signedURL") or result.get("signedUrl")
                return getattr(result, "signed_url", None)
            except Exception:
                return None
    return None
