import 'package:flutter/material.dart';
import '../services/api_service.dart';

class AddCardScreen extends StatefulWidget{const AddCardScreen({super.key});@override State<AddCardScreen> createState()=>_AddCardScreenState();}
class _AddCardScreenState extends State<AddCardScreen>{
 final form=GlobalKey<FormState>(); final api=ApiService(); bool saving=false;
 final sport=TextEditingController(text:'basketball'),season=TextEditingController(),manufacturer=TextEditingController(),product=TextEditingController(),setName=TextEditingController(),number=TextEditingController(),subject=TextEditingController(),team=TextEditingController(),parallel=TextEditingController(),serialActual=TextEditingController(),storage=TextEditingController();
 bool rookie=false,insert=false,auto=false,relic=false,serialNumbered=false;
 Widget field(String label,TextEditingController c,{bool required=false})=>TextFormField(controller:c,decoration:InputDecoration(labelText:label),validator:required?(v)=>(v==null||v.trim().isEmpty)?'Pflichtfeld':null:null);
 Future<void> save() async{if(!form.currentState!.validate())return;setState(()=>saving=true);try{await api.addManual({'identity':{'sport':sport.text.trim(),'season':season.text.trim().isEmpty?null:season.text.trim(),'manufacturer':manufacturer.text.trim().isEmpty?null:manufacturer.text.trim(),'product_line':product.text.trim().isEmpty?null:product.text.trim(),'set_name':setName.text.trim().isEmpty?null:setName.text.trim(),'card_number_printed':number.text.trim().isEmpty?null:number.text.trim(),'primary_subject_name':subject.text.trim(),'team_name':team.text.trim().isEmpty?null:team.text.trim(),'parallel_name':parallel.text.trim().isEmpty?null:parallel.text.trim(),'is_rookie':rookie,'is_insert':insert,'is_autograph':auto,'is_relic':relic,'is_serial_numbered':serialNumbered},'instance':{'serial_number_actual':serialActual.text.trim().isEmpty?null:serialActual.text.trim(),'storage_location':storage.text.trim().isEmpty?null:storage.text.trim()}});if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}finally{if(mounted)setState(()=>saving=false);}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Karte detailliert erfassen')),body:Form(key:form,child:ListView(padding:const EdgeInsets.all(16),children:[
   const Text('Identität',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),field('Sport',sport,required:true),field('Saison (z. B. 2024-25)',season),field('Hersteller',manufacturer),field('Produktlinie (Prizm, Select, Optic …)',product),field('Set / Subset',setName),field('Kartennummer',number),field('Spieler / Hauptmotiv',subject,required:true),field('Team',team),field('Parallel / Variation',parallel),
   SwitchListTile(value:rookie,onChanged:(v)=>setState(()=>rookie=v),title:const Text('Rookie / RC')),SwitchListTile(value:insert,onChanged:(v)=>setState(()=>insert=v),title:const Text('Insert')),SwitchListTile(value:auto,onChanged:(v)=>setState(()=>auto=v),title:const Text('Autograph')),SwitchListTile(value:relic,onChanged:(v)=>setState(()=>relic=v),title:const Text('Relic / Patch')),SwitchListTile(value:serialNumbered,onChanged:(v)=>setState(()=>serialNumbered=v),title:const Text('Serial numbered')),
   field('Tatsächliche Seriennummer (z. B. 17/99)',serialActual),field('Lagerort / Box',storage),const SizedBox(height:20),FilledButton.icon(onPressed:saving?null:save,icon:const Icon(Icons.save),label:Text(saving?'Speichern …':'Speichern'))
 ])));
}
